# Grundlagen numpy

## numpy

Numpy ist eines der ersten Tools, welches man auf dem Weg Richtung Deep Learning kennenlernt. 

In [1]:
import numpy as np

## Daten Typen

Ein Skalar ist eine einzelne Zahl: _"Ein Skalar ist eine mathematische Größe, die allein durch die Angabe eines Zahlenwertes charakterisiert ist"_ (https://de.wikipedia.org/wiki/Skalar_(Mathematik))

### Vektoren

Ein Vektor hat nur eine Dimension. Entweder als Zeile oder Spalte geschrieben

\begin{vmatrix}
1 \\
2 \\
3
\end{vmatrix}

\begin{vmatrix}
1 && 2 && 3
\end{vmatrix}

In [3]:
a = np.array([1,2,3])
a.shape

(3,)

Das Ergebnis ist "(3,)" da es nur eine Dimension gibt und somit ein Vektor der länge drei.

### Matrizen

In [7]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

Das Ergebnis hier ist "(2, 3)" da es zwei Zeilen und jeweils 3 Spalten gibt. Also eine Matrix der Größe 2x3 und somit haben wir eine Matrix mit zwei Dimensionen. 

Üblicherweise wird immer erst die Anzahl der Zeilen und dann der Spalten genannt. Vor allem auch bei der Angabe von Indizes, allerdings wird dabei immer bei 1 gestartet und nicht bei 0 wie in der Informatik üblich.

\begin{vmatrix}
1 && 2 && 3\\
2 \\
3
\end{vmatrix}

Als nächstes folgt eine n-Dimensionale Matrix, diese wird dann auch "Tensor" genannt.

### Tensor

In [4]:
a = np.array([[[[1],[2],[3]], [[3],[4],[5]]]])
a.shape

(1, 2, 3, 1)

## Operationen

### reshape

"reshape" ermöglicht das umkehren von Matrizen, also zum Beispiel können wir aus unserem Vektor der Länge 3 eine 3x1 Matrix und eine 1x3 Matrix machen. 

In [8]:
a = np.array([1,2,3])
a.shape

(3,)

In [11]:
b = a.reshape(1,3)
b.shape

(1, 3)

In [12]:
c = a.reshape(3,1)
c.shape

(3, 1)

### Element basierte Addition

In [13]:
values = [1,2,3]
values = np.array(values) + 10

values

array([11, 12, 13])

Das gleiche gilt natürlich auch für alle andere Rechenarten.

In [17]:
multi = values * 5
multi

array([55, 60, 65])

Da es hier aber schon als ndarray vorliegt, können wir es auch direkt mit 5 multiplizieren.

In [18]:
factor = np.array([3,4,5])
result = multi * factor

result

array([165, 240, 325])

Funktioniert allerdings nur, wenn beide Vektoren / Matrizen die selbe Größe haben.

### Matrix Produkt

Matrizen Multiplikation kann wie oben beschrieben funktionieren, aber meistens wird über das Matrixprodukt gesprochen. Mehr Informationen hier: https://de.wikipedia.org/wiki/Matrizenmultiplikation. 

Wichtig hierbei, es funktioniert nicht mehr, wenn beide Matrizen die selbe Größe haben. 
3x5 * 5x3 funktioniert (die beiden inneren Zahlen müssen identisch sein) 

Numpy hat auch hierfür eine Funktion, genannt matmul:

In [19]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [20]:
b = np.array([[1,2],[3,4],[5,6]])
b.shape

(3, 2)

In [21]:
c = np.matmul(a,b)
c

array([[22, 28],
       [49, 64]])

In [24]:
c.dot(c)

array([[1856, 2408],
       [4214, 5468]])

Das Skalarprodukt einer 2x2 Matrix kann auch direkt aufgerufen werden. (https://de.wikipedia.org/wiki/Skalarprodukt)

### Transpose

Um die Zeilen und Spalten einer Matrix "umzudrehen", gibt es Transpose

In [26]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [27]:
b = a.T
b.shape

(3, 2)

In [28]:
b

array([[1, 4],
       [2, 5],
       [3, 6]])